
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    registerWithEureka: false
    fetchRegistry: false
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server