
server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:

    instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/